#!/bin/bash

# >>> CRAPPY NVM INITIALIZE >>>
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
export PATH=$(awk_magic ":$PATH")
# <<< GARBAGE NVM initialize <<<
